create table if not exists public.changeover_records (
  id bigint primary key generated by default as identity,
  type text not null,
  plant text not null,
  workshop text,
  process text,
  line text,
  from_model text,
  to_model text,
  classification text,
  time timestamp,
  duration int2,
  tean text,
  role text
);

alter table public.changeover_records enable row level security;

drop policy if exists "Allow anon read changeover records"
  on public.changeover_records;

create policy "Allow anon read changeover records"
  on public.changeover_records
  for select
  to anon
  using (true);

drop policy if exists "Allow anon insert changeover records"
  on public.changeover_records;

create policy "Allow anon insert changeover records"
  on public.changeover_records
  for insert
  to anon
  with check (true);
