create table if not exists public.changeover_records (
  id bigint primary key generated by default as identity,
  type text not null,
  plant text not null,
  workshop text,
  process text,
  line text,
  from_model text,
  to_model text,
  classification text,
  status text default 'Submitted',
  time timestamp,
  duration int2,
  actual_duration int2,
  team text,
  role text,
  unplanned_category text,
  unplanned_reason text,
  note text
);

alter table public.changeover_records
  add column if not exists status text default 'Submitted',
  add column if not exists actual_duration int2,
  add column if not exists team text,
  add column if not exists unplanned_category text,
  add column if not exists unplanned_reason text,
  add column if not exists note text;

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'changeover_records'
      and column_name = 'tean'
  ) then
    execute 'update public.changeover_records set team = coalesce(team, tean) where team is null';
    execute 'alter table public.changeover_records drop column tean';
  end if;
end $$;

alter table public.changeover_records enable row level security;

drop policy if exists "Allow anon read changeover records"
  on public.changeover_records;

create policy "Allow anon read changeover records"
  on public.changeover_records
  for select
  to anon
  using (true);

drop policy if exists "Allow anon insert changeover records"
  on public.changeover_records;

create policy "Allow anon insert changeover records"
  on public.changeover_records
  for insert
  to anon
  with check (true);



drop policy if exists "Allow anon update changeover records"
  on public.changeover_records;

create policy "Allow anon update changeover records"
  on public.changeover_records
  for update
  to anon
  using (true)
  with check (true);

drop policy if exists "Allow anon delete changeover records"
  on public.changeover_records;

create policy "Allow anon delete changeover records"
  on public.changeover_records
  for delete
  to anon
  using (true);
